;;; wallpaper-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wallpaper.el

(autoload 'wallpaper-set-wallpaper "wallpaper" "\
Set the wallpaper.

This function will either choose a random wallpaper from
`wallpaper-cycle-directory' or use the wallpapers listed in
`wallpaper-static-wallpapers'." t)
(defvar wallpaper-cycle-mode nil "\
Non-nil if Wallpaper-Cycle mode is enabled.
See the `wallpaper-cycle-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `wallpaper-cycle-mode'.")
(custom-autoload 'wallpaper-cycle-mode "wallpaper" nil)
(autoload 'wallpaper-cycle-mode "wallpaper" "\
Toggle Wallpaper Cycle mode.

This mode will activate a timer which will call `wallpaper-set-wallpaper'
at the interval defined by `wallpaper-cycle-interval'.  See function
`wallpaper--toggle-cycle' for more information.

This is a global minor mode.  If called interactively, toggle the
`Wallpaper-Cycle mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='wallpaper-cycle-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(defvar wallpaper-per-workspace-mode nil "\
Non-nil if Wallpaper-Per-Workspace mode is enabled.
See the `wallpaper-per-workspace-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `wallpaper-per-workspace-mode'.")
(custom-autoload 'wallpaper-per-workspace-mode "wallpaper" nil)
(autoload 'wallpaper-per-workspace-mode "wallpaper" "\
Toggle Wallpaper Per Workspace mode.

This mode will set specific wallpapers based on the current workspace.
See `wallpaper-per-workspace-alist' and `wallpaper-per-workspace-get'.

This is a global minor mode.  If called interactively, toggle the
`Wallpaper-Per-Workspace mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='wallpaper-per-workspace-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "wallpaper" '("wallpaper-"))

;;; End of scraped data

(provide 'wallpaper-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wallpaper-autoloads.el ends here
