;;; dictionary-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dictionary.el

(autoload 'dictionary-mode "dictionary" "\
This is a mode for searching a dictionary server implementing
 the protocol defined in RFC 2229.

 This is a quick reference to this mode describing the default key bindings:

 * q close the dictionary buffer
 * h display this help information
 * s ask for a new word to search
 * d search the word at point
 * n or Tab place point to the next link
 * p or S-Tab place point to the prev link

 * m ask for a pattern and list all matching words.
 * D select the default dictionary
 * M select the default search strategy

 * Return or Button2 visit that link
 * M-Return or M-Button2 search the word beneath link in all dictionaries
 ")
(autoload 'dictionary "dictionary" "\
Create a new dictonary buffer and install dictionary-mode" t)
(autoload 'dictionary-search "dictionary" "\
Search the `word' in `dictionary' if given or in all if nil.  
It presents the word at point as default input and allows editing it.

(fn WORD &optional DICTIONARY)" t)
(autoload 'dictionary-lookup-definition "dictionary" "\
Unconditionally lookup the word at point." t)
(autoload 'dictionary-match-words "dictionary" "\
Search `pattern' in current default dictionary using default strategy.

(fn &optional PATTERN &rest IGNORED)" t)
(autoload 'dictionary-mouse-popup-matching-words "dictionary" "\
Display entries matching the word at the cursor

(fn EVENT)" t)
(autoload 'dictionary-popup-matching-words "dictionary" "\
Display entries matching the word at the point

(fn &optional WORD)" t)
(autoload 'dictionary-tooltip-mode "dictionary" "\
Display tooltips for the current word

(fn &optional ARG)" t)
(autoload 'dictionary-tooltip-mode "dictionary" "\
Display tooltips for the current word

(fn &optional ARG)" t)
(autoload 'global-dictionary-tooltip-mode "dictionary" "\
Enable/disable dictionary-tooltip-mode for all buffers

(fn &optional ARG)" t)
(register-definition-prefixes "dictionary" '("dictionary-" "global-dictionary-tooltip-mode"))

;;; End of scraped data

(provide 'dictionary-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dictionary-autoloads.el ends here
