theme="catppuccin_frappe"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.file-picker]
hidden = true
