#!/bin/sh

# some useful options (man zshoptions)
autoload -U colors && colors

# History
export HISTSIZE=10000
export SAVEHIST="$HISTSIZE"
export HISTFILE=$XDG_DATA_HOME/zsh/.zsh_history

# Useful Functions
# [ -f "${ZDOTDIR}/functionrc" ] && source "${ZDOTDIR}/functionrc"
[ -f "${ZDOTDIR}/aliasrc" ] && source "${ZDOTDIR}/aliasrc"
[ -f "${ZDOTDIR}/optionrc" ] && source "${ZDOTDIR}/optionrc"

# function yy() {
#     local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
#     yazi "$@" --cwd-file="$tmp"
#     if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
#     cd -- "$cwd"
#     fi
#     rm -f -- "$tmp"
# }

source ~/.local/share/zap/zap.zsh

# Plugins
# For more pluins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions
plug "marlonrichert/zsh-autocomplete"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-completions"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"
plug "ael-code/zsh-colored-man-pages"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.fzf/shell/completion.zsh ] && source ~/.fzf/shell/completion.zsh
[ -f ~/.fzf/shell/key-bindings.zsh ] && source ~/.fzf/shell/key-bindings.zsh
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'
export FZF_DEFAULT_OPTS="-m --height 50% --layout=reverse --border --inline-info"

# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# Print tree structure in the preview window
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'tree -C {}'"

# Source files
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"

# Completions
fpath=(~/.config/zsh/zsh-completions/src $fpath)

autoload -U compinit
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' list-colors "${(s.:.)--color=auto}"
zstyle ':completion:*' rehash true
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

_comp_options+=(globdots)

autoload edit-command-line; zle -N edit-command-line
zle_highlight=('paste:none')

# Bindkey
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Key-bindings
bindkey -v

export PATH="/Applications/Emacs.app/Contents/MacOS:$PATH"
export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="Development/coding/zls/zig-out/bin:$PATH"

