;;; window-tool-bar-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from window-tool-bar.el

(autoload 'window-tool-bar-string "window-tool-bar" "\
Return a (propertized) string for the tool bar.

This is for when you want more customizations than the command
`window-tool-bar-mode' provides.  Commonly added to the variable
`tab-line-format', `header-line-format', or `mode-line-format'")
(autoload 'window-tool-bar-mode "window-tool-bar" "\
Toggle display of the tool bar in the tab line of the current buffer.

This is a minor mode.  If called interactively, toggle the
`Window-Tool-Bar mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `window-tool-bar-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-window-tool-bar-mode 'globalized-minor-mode t)
(defvar global-window-tool-bar-mode nil "\
Non-nil if Global Window-Tool-Bar mode is enabled.
See the `global-window-tool-bar-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-window-tool-bar-mode'.")
(custom-autoload 'global-window-tool-bar-mode "window-tool-bar" nil)
(autoload 'global-window-tool-bar-mode "window-tool-bar" "\
Toggle Window-Tool-Bar mode in all buffers.
With prefix ARG, enable Global Window-Tool-Bar mode if ARG is
positive; otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Window-Tool-Bar mode is enabled in all buffers where
`window-tool-bar--turn-on' would do it.

See `window-tool-bar-mode' for more information on Window-Tool-Bar
mode.

(fn &optional ARG)" t)
(register-definition-prefixes "window-tool-bar" '("window-tool-bar-"))

;;; End of scraped data

(provide 'window-tool-bar-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; window-tool-bar-autoloads.el ends here
